openqa_review/openqa_review.py
=> Let --query-issue-status" arg implie --bugrefs

openqa_review/openqa_review.py
Prevents wrong interpretation of unexpected bugref entries. Actually this is a
workaround for sloppy openQA behaviour, e.g. for comments referencing multiple
bugs.
=> Be more strict about bugrefs read on openQA webpages

.gitignore, openqa_review/openqa_review.py, tests/tags_labels/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%5B%7B%22ids%22%3A%5B9315715%5D%7D%5D, tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1507%26groupid%3D25, tests/tags_labels/report25_bugrefs.md, tests/tags_labels/report25_bugrefs_query_issues.md
=> Use Objects to handle Issues and ArchReport

openqa_review/openqa_review.py, tests/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20160916%26groupid%3D4, tests/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20160917%26groupid%3D4, tests/https%3A::openqa.opensuse.org:group_overview:4, tests/test_openqa_review.py
This was causing an error when parsing https://openqa.opensuse.org/group_overview/4
=> Fix arch matching

openqa_review/openqa_review.py
`")` would indicate the end of the link title.
=> Fix ") in issue subject breaking markdown

openqa_review/openqa_review.py
Accept the new and the old format for now.
See https://github.com/os-autoinst/openQA/pull/965
=> Prepare for upcoming openQA changes regarding wellformed json

openqa_review/browser.py, tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1508%26groupid%3D25, tests/tags_labels/report25_bugrefs_build1508.md, tests/test_openqa_review.py
=> Handle broken bugrefs gracefully

openqa_review/openqa_review.py, tests/report25_T.md, tests/report25_TT.md, tests/report25_TTT.md, tests/report25_terse.md, tests/tags_labels/report25_T_bugrefs.md, tests/tags_labels/report25_bugrefs.md, tests/tags_labels/report25_bugrefs_build1508.md, tests/tags_labels/report25_bugrefs_query_issues.md, tests/tags_labels/report25_bugrefs_query_issues_filter_closed.md, tests/tags_labels/report25_bugrefs_query_issues_filter_unassigned.md, tests/tags_labels/report_link_new_issue/report25_bugrefs_bug_link_new_issue.md
See https://github.com/okurz/openqa_review/issues/62
Not tested yet, I'm currently still figuring out how to run the script and its test suite locally.
=> Fix broken HTML

openqa_review/openqa_review.py
This time an issue has been encountered in a progress ticket subject line.
=> Fix non-ascii encoding problems in the whole generated report

openqa_review/browser.py
ConnectionError occurred while trying to add a comment on an issue
tracker. The commit allows to catch the exception and to trigger more
attempts.
Related ticket: https://github.com/okurz/openqa_review/issues/104
=> Handle connection error while sending POST

openqa_review/openqa_review.py, tests/skip-passed/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20210514.7.81%26groupid%3D68, tests/skip-passed/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20210515.7.81%26groupid%3D68, tests/skip-passed/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20210522%26groupid%3D4, tests/skip-passed/:tests:overview%3Fdistri%3Dopensuse%26version%3DTumbleweed%26build%3D20210523%26groupid%3D4, tests/skip-passed/https%3A::openqa.opensuse.org:group_overview:4.json, tests/skip-passed/https%3A::openqa.opensuse.org:group_overview:68.json, tests/skip-passed/report-68-4.md, tests/test_openqa_review.py
Issue: https://progress.opensuse.org/issues/92957
=> Add option --skip-passed to skip passed reports

openqa_review/browser.py
The retries don't preserve the exception or status code if we hit the for/else branch. Since we may not have a request I'm using a string.
=> Surface last error from browser.get

openqa_review/browser.py
=> Replace retry loop with Retry from urllib3

openqa_review/openqa_review.py, tests/tags_labels/:tests:384330:file:select_patterns_and_packages-125.txt
Ticket: https://progress.opensuse.org/issues/93724 / #146
=> Fix #146: Properly handle bugrefs in softfails

openqa_review/openqa_review.py
Related progress issue: https://progress.opensuse.org/issues/98457
=> Add suggestion how to prevent bug reminder comments

openqa_review/openqa_review.py, tests/test_openqa_review.py
Fix problems introduced by #197 which has been merged without working CI checks.
=> Fix coverage check and linter check

.mergify.yml
As we now use GHA we can also use that in mergify.
=> Add mergify configuration based on os-autoinst/scripts

.github/workflows/python-package.yaml, openqa_review/openqa_review.py, openqa_review/tumblesle_release.py
I found the answer in this post which had zero points so far :)
https://stackoverflow.com/a/51344189/93745
Issue: https://progress.opensuse.org/issues/102641
=> t: Fix import so doctests can run

tests/test_openqa_review.py, tox.ini
Issue: https://progress.opensuse.org/issues/102350
=> Add coverage for doctests

openqa_review/openqa_review.py, tests/test_openqa_review.py
Related issue: https://progress.opensuse.org/issues/106909
=> Reminder comments point to specific openQA test details steps or openQA comments

openqa_review/openqa_review.py, tests/test_openqa_review.py
See https://progress.opensuse.org/issues/113611
=> Re-open issues when adding reminder comments

openqa_review/openqa_review.py, tests/test_openqa_review.py
Related progress issue: https://progress.opensuse.org/issues/113611
=> Add command line option for "reopen"

openqa_review/openqa_review.py, tests/test_openqa_review.py
* Make checks for current progress/bugzilla issue status case-insensitive
* See https://progress.opensuse.org/issues/113611
=> Fix case-sensitivity issue that prevented re-opening tickets to work

openqa_review/openqa_review.py
pkg_resources.parse_version does not support strings like 12-SP5-0456 anymore
=> Fix sorting version strings
