- nosier
- openqa_review/openqa_review.py
- tests/report25_T.md
- tests/report25_TT.md
- tests/report25_TTT.md
- tests/report25_terse.md
For openqa_review it is currently not possible to distinguish easily between
a product issue and a openQA issue so better leave the choice to the user.
The proposed workflow is as follows:
- The reviewer lets openqa_review create a template for a product, e.g. with
openqa_review --host openqa.suse.de -j Server \
--against-reviewed last -TTTT > report_server.md
- The reviewer investigates all issues mentioned under "TODO" and decides if
they are either "product" or "openQA" issue and moves them to the 
corresponding block
- The reviewer does further tuning of the report before publishing
> Do not distinguish between product and openqa issues for now

- openqa_review/openqa_review.py
python-requests must be installed via RPM to be able to use the suse ca bundle.
Also the suse ca certificate rpm should be installed.
This applies primarily for openqa.suse.de.
> Fix insecure ssl warning

- openqa_review/openqa_review.py
- Remove broken --base-url parameter
- No need for redundant --host param
when url is specified via --job-group-urls
- Add global openqa_browser for all queries to openqa instance.
It will make sure that relative urls are prepended with the correct root_url.
> Simplify script usage

- openqa_review/openqa_review.py
Sometimes there are build with inconsistent
values for this attribute in the same job group.
This patch will prevent exceptions for such cases.
> Try to get distri/version for each build

- openqa_review/openqa_review.py
Fixes issue as described in E-Mail `2908257.oPA3PKhX0P@linux-28d6.suse`
> Use blank build value without version prefix

- call_tests
- openqa_review/openqa_review.py
- pytest_no_webtest
- tests/test_openqa_review.py
- tox.ini
With the current testing approach testing against the web interface is
not done with the webtests so they are untested and not necessary.
> Remove unused webtests

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1508%26groupid%3D25
- tests/tags_labels/report25_bugrefs_build1508.md
Include #0 ticket references in the report, so not hiding from
reviewers, while fooling ttm.
See https://github.com/okurz/openqa_review/issues/77 and
[poo#35758](https://progress.opensuse.org/issues/35758).
Example output:
```bash
**Date:** 2018-05-11 - 16:10
**Build:** 609.1 (reference 609.1)
---
**Arch:** x86_64
**Status: <span style="color: green;">Green</span>**
**Existing Product bugs:**
* [fake](http://gershwin.arch.suse.de/tests/366 "Failed modules: logpackages") -> [boo#0](https://bugzilla.opensuse.org/show_bug.cgi?id=0) (NOTE: boo#0/bsc#0/poo#0 label used, please review. Consider creating progress ticket for the investigation)
---
```
> Process poo#0/boo#0/bsc#0 ticket labels

- README.md
The python requests module uses the `certifi` CA store by default to verify all TLS requests done by it.
This can cause problems if `openqa-review` has to access resources protected by custom TLS certificates and results in:
```
openqa_review.browser.DownloadError: Request to https://openqa.example.com/group_overview/110.json was not successful after multiple retries, giving up
```
> Add hint for custom CA store locations

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:684839
- tests/tags_labels/:tests:684839:file:details-zypper_info.json
- tests/tags_labels/:tests:684839:file:zypper_info-4.txt
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1507%26groupid%3D25
- tests/tags_labels/report25_T_bugrefs_softfails.md
The commit allows soft-fail reference
in test without a valid bugref to be
reported in the generated report.
Related ticket: https://github.com/okurz/openqa_review/issues/76
> Add soft-fails without bugref to openqa report

- openqa_review/browser.py
The commit adds ability for
openqa-review script to retry
connect to the mentioned url
instead of failing while 504
Gateway Timeout Error occurred
> Add request retry on HTTP error 504

- openqa_review/openqa_review.py
- tests/tags_labels/report25_bugrefs_query_issues.md
- tests/test_openqa_review.py
The PR adds proper logic for handling openQA issues with bugref but without valid bugid.
Previously, an AttributeError occurred due to called 'bugid' attribute of 'Issue' object, but 'bugid' was not initialized.
The issue happened only in case, if openqa_report was executed with 'query_issue_status' parameter and openQA issue has bugref in invalid form (e.g. sentence instead of poo#123, boo#123).
>  Fix report generation for issues without bugid

- openqa_review/openqa_review.py
- tests/tags_labels/:jsonrpc.cgi%3Fmethod%3DBug.comments%26params%3D%255B%257B%2522ids%2522%253A%2B%255B931572%255D%257D%255D
- tests/test_openqa_review.py
When openQA issue does not have a valid bugref,
it is added as 'product' issue. Reminder comment
script goes through the 'product' issues and looks
for a last comment. It will fail on  assertion if issue
type is not 'bugzilla'.
The commit resolves the issue by skipping
'product' issues with invalid issue type.
>  Fix reminder comment when issue type is not valid

- openqa_review/openqa_review.py
- tests/tags_labels/report25_bugrefs_query_issues_filter_unassigned.md
- tests/test_openqa_review.py
The commit adds additional checks for
an issue properties existence in
order to avoid AttributeError.
That happens when issue does not have
a valid bugref and as a consequence it does
not have some attributes, such as status,
assignee.
> Fix report filter for issues with not valid bugref

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:384325
- tests/tags_labels/:tests:447901
- tests/tags_labels/report_link_new_issue/:tests:585912
The layout of Results Page in openQA UI was changed in the latest release. The PR adapts openqa_review script to the changes and updates the appropriate tests data accordingly.
I've tested that changes by running script locally with the exact parameters as on production and the report was generated without errors.
> Adapt script to the openQA layout changes

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:684839:file:zypper_info-4.txt
- tests/tags_labels/report25_T_bugrefs_softfails.md
- tests/tags_labels/report25_bugrefs_query_issues.md
- tests/tags_labels/report25_bugrefs_query_issues_filter_unassigned.md
The PR adds a function, that parses soft fail messages and formats
all found urls using markdown, e.g.` [http://example.com](http://example.com)` 
and the appropriate tests.
It allows to show the urls as links in the report instead of showing them
as a plain text.
**For reviewers:** Just to prevent questions related to the data, that I've updated in the test (`for Leap:15.0:Ports aarch64 and ppc64le, do not enable source repo, waiting for https://progress.opensuse.org/issues/36256 to be solved, and also http://fate.suse.com/12345`).
It contains two links instead of one to cover more cases, such as:
* http and http**s**;
* positioning of the link (in the middle of message and in the end);
* to check that several links, but not only one could be parsed and formatted properly;
* to ensure …
> Format all urls in softfail message using markdown

- openqa_review/browser.py
Some reports failed to be generated due to 503 error, while accessing openQA URLs.
The PR adds an ability to reconnect on 503 error in the same way as it was already made for 502 and 504 errors.
> Add request retry on HTTP error 503

- openqa_review/openqa_review.py
- tests/test_openqa_review.py
- tox.ini
As we have a custom ignore list of policies we now also need to choose
explicitly among W503 or W504. I understood in particular
https://lintlyci.github.io/Flake8Rules/rules/W503.html and some related
discussion pages as W504 is the way to go so ignoring W503.
> Fix python style checks for new flake8

- openqa_review/openqa_review.py
- tests/https%3A::openqa.opensuse.org:group_overview:26.json
Fixes #111
Ticket: https://progress.opensuse.org/issues/44648
This will make sure that build 98 will be sorted before 102.
> Use version compare algo to compare builds

- bin/openqa-review-daily-email
- openqa_review/openqa_review.py
It is hard to fix these errors on python2 and we thought we caught them all
already in before. Hopefully this helps again. I am not really sure because I
could only reproduce the problem based on the complete report generation from
https://openqa.suse.de not relying on any locally saved files. Probably the
content is still encoded differently when read remotely or from files. Each
run took to check takes 40-50 minutes so it was a lengthly fixing process :)
> Fix sporadic ASCII encoding errors in python2 on complete report

- openqa_review/openqa_review.py
- tests/report25_T.md
- tests/report25_TT.md
- tests/report25_TTT.md
- tests/report25_terse.md
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1500%26groupid%3D25
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1507%26groupid%3D25
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1508%26groupid%3D25
- tests/tags_labels/report25_T_bugrefs.md
- tests/tags_labels/report25_T_bugrefs_softfails.md
- tests/tags_labels/report25_bugrefs.md
- tests/tags_labels/report25_bugrefs_abbreviated.md
- tests/tags_labels/report25_bugrefs_build1508.md
- tests/tags_labels/report25_bugrefs_query_issues.md
- tests/tags_labels/report25_bugrefs_query_issues_filter_closed.md
- tests/tags_labels/report25_bugrefs_query_issues_filter_unassigned.md
- tests/tags_labels/report_link_new_issue/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1500%26groupid%3D25
- tests/tags_labels/report_link_new_issue/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1507%26groupid%3D25
- tests/tags_labels/report_link_new_issue/report25_bugrefs_bug_link_new_issue.md
Merging this patch the report will include listing skipped tests per architecture.  The results comes into the interesting_states dict which is store the state between the current and the previous job. however the skipped tests output considers only the current job and it does not attempt any comparison with the previous state( difference between the skipped tests)
> Generate report including the skipped test

- openqa_review/openqa_review.py
- tests/tags_labels/report25_T_bugrefs.md
- tests/tags_labels/report25_T_bugrefs_softfails.md
- tests/tags_labels/report25_bugrefs.md
- tests/tags_labels/report25_bugrefs_abbreviated.md
- tests/tags_labels/report25_bugrefs_build1508.md
- tests/tags_labels/report25_bugrefs_query_issues.md
- tests/tags_labels/report25_bugrefs_query_issues_filter_closed.md
- tests/tags_labels/report25_bugrefs_query_issues_filter_unassigned.md
- tests/tags_labels/report_link_new_issue/report25_bugrefs_bug_link_new_issue.md
following up of #37429 this PR is fixing the issues that appeared in it. Particularly, the list should not show duplicated tests. The reason was that it regex'ed for skipped tests in the whole page without taking care of the arch. report will display skipped test per arch now, fetching the links to those tests as well.
> Skipped tests includes links

- openqa_review/openqa_review.py
Test module names have an appended "#<nr>" when scheduled multiple
times. By quoting the names accordingly we generate valid URLs.
Tested locally with
```
openqa_review/openqa_review.py -vvvv -J http://openqa.suse.de/group_overview/265 -TTTTT -R -r --include-softfails -n --arch s390x
```
> Fix error on repeated test modules when reading out details from soft-fail bugrefs

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:684839:file:details-zypper_info.json
- tests/tags_labels/:tests:684839:file:zypper_info-4.txt
This change is necessary due to changes on the openQA side. The text file might not be available anymore. Its content is instead directly incorporated into the details JSON document.
See https://progress.opensuse.org/issues/69058#note-1
---
Let's see whether the CI checks still pass. I had troubles running the tests locally. At least `python3 openqa_review/openqa_review.py -vvvv -n -r -T --no-empty-sections --include-softfails -J https://openqa.suse.de/group_overview/290` shows no 404 errors anymore.
> Read text data from details JSON if present

- openqa_review/openqa_review.py
This problem happened since about a month during every run but only on
openqa.suse.de data as it seems. The problem was caused by a lot of
escaped text in test module details in conjunction with our code trying
to parse the json document as text first and then parsing as JSON when
escaped characters are already evaluated by python when they should not
have been touched at all. Better we use the `get_json` method of our
browser objects directly to prevent this.
> Fix "ValueError: Expecting ',' delimiter: line 1..." when trying to parse soft-fail details

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:1316928
- tests/tags_labels/:tests:1316928:file:details-shutdown.json
- tests/tags_labels/:tests:overview%3Fdistri%3Dopensuse%26version%3D42.1%26build%3D1507%26groupid%3D25
- tests/tags_labels/report25_T_bugrefs_softfails.md
- tests/tags_labels/report25_bugrefs_query_issues.md
Reproduced a problem observed in production locally with:
```
mkdir tmp_no_found_softfail_ref
python3 openqa_review/openqa_review.py -J https://openqa.opensuse.org/group_overview/50 --arch x86_64 -vv -TTTT --include-softfails --bugrefs --no-empty-sections --save --save-dir tmp_no_found_softfail_ref
python3 openqa_review/openqa_review.py -J https://openqa.opensuse.org/group_overview/50 --arch x86_64 -vv -TTTT --include-softfails --bugrefs --no-empty-sections --load --load-dir tmp_no_found_softfail_ref
```
> Fix readout of custom softfail references

- openqa_review/openqa_review.py
The username `openqa_review` doesn't have permission to add a private
comment to Bugzilla. And `openqa_review` only can get the public
comments from Bugzilla. So when adding a private comment, Bugzilla will
return an error `500 Server Error: Internal Server Error`.
Test result: https://bugzilla.suse.com/show_bug.cgi?id=1005824
See: https://progress.opensuse.org/issues/75214
> Change comments to not private when adding comments

- .travis.yml
- README.md
- tox.ini
Fixes [poo#89206](https://progress.opensuse.org/issues/89206)
> Drop Python 2.7 support from CI and tox

- README.md
Related progress issue: https://progress.opensuse.org/issues/93423
> Update travis CI URLs after migration to travis-ci.com

- openqa_review/tumblesle_release.py
Otherwise the following deprecation warning is visible:
tests/test_tumblesle_release.py::test_compare_old_released_with_release_info_against_new_good_yields_release
$PWD/.tox/py38/lib/python3.8/site-packages/openqa_review/tumblesle_release.py:253: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
release_info = yaml.load(release_info_file)
> Specify Loader=yaml.SafeLoader explicitly

- tests/test_openqa_review.py
This will prevent confusion when the testsuite tries to
import the system wide installed `openqa_review` or fail
when called directly or with `py.test` insted of `tox`.
> Fix relative import path for directly called testsuite

- openqa_review/browser.py
It's a good practice for bots to let servers know what client they
are using.
Currently it just says "python-requests/x.y"
It would even be better to add the version, but I don't think we
have that right now.
> Add User-Agent header to HTTP requests

- openqa_review/openqa_review.py
Currently a KeyError is catched, but that might be also a KeyError
happening inside filter_report().
For developers this can lead to such a confusing error message:
No such filter 'unassigned'
Available filters: closed, unassigned
Since we can easily check if a key exists in a dict, we don't need
exception handling for that.
> Improve handling of --filter

- openqa_review/openqa_review.py
- tests/tags_labels/:tests:384330:file:select_patterns_and_packages-125.txt
- tests/tags_labels/report25_T_bugrefs_softfails.md
- tests/tags_labels/report25_bugrefs_query_issues.md
Ticket: https://progress.opensuse.org/issues/93724
Bugrefs eg bsc1234 instead bsc#1234 happen eg when using
softfail needles as filenames don't contain hashes.
> Fix loading bug info for hashless bugrefs

- openqa_review/browser.py
In other functions we also uses raise_for_status, which is an optional mechanism to get exceptions for failed requests.
> Raise HTTP status errors in browser content

- openqa_review/browser.py
- openqa_review/openqa_review.py
The old way passing it via BASIC auth doesn't work anymore
Ticket: https://progress.opensuse.org/issues/93943
> Ensure that the progress api key is always provided via header

- openqa_review/browser.py
The timeout of 2.5 seconds is too low for when OSD is under heavy load. Testing at different times during the day suggests 10 is much better.
Run this repeatedly. When OSD is under high load there's a lot of timeouts and it may not catch up even after 7 attempts with the current timeout.
python3 openqa_review/openqa_review.py --host https://openqa.suse.de -n -r -T --query-issue-status --no-empty-sections --include-softfails --run
> Bump timeout for individual browser.get requests

- openqa_review/browser.py
This can mean a request failed with a 404:
Request to https://openqa.suse.de/tests/5989057/file/details-bootloader_zkvm#1.json failed:
404 Client Error: Not Found for url: https://openqa.suse.de/tests/5989061/file/details-bootloader_zkvm#1.json
We should regard this as an error to be reviewed manually in the generated report. The URL will be visible there and we can still continue with the generation of the report.
python3 openqa_review/openqa_review.py --host https://openqa.suse.de -n -r -T --query-issue-status --no-empty-sections --include-softfails --running-threshold=2 --exclude-job-groups '^(Released|Development|old|EOL)' -J https://openqa.suse.de/group_overview/143
This should include the above error message without raising an …
> Catch HTTPError and raise DownloadError

- openqa_review/openqa_review.py
e.g. `jsc#ABC-123`
Issue: https://progress.opensuse.org/issues/95989
Additionally improve logging in case the regex does not match, so that
we immediately see what didn't match and why.
If necessary, I will try to add a test, but will be afk for a few hours and wanted to push a fix ASAP.
> Improve handling of unknown or unexpected bugrefs

- openqa_review/browser.py
Observing [pipeline runs on internal GitLab](https://gitlab.suse.de/openqa/openqa-review/-/pipelines/184191) I saw several timeouts. So attempting to remedy that by increasing from `10s` to `30s`. Not sure we can do much else here.
> Increase browser.get timeout from 10 to 30

- openqa_review/browser.py
In this case we can't recover, but we can still log the error and continue with other reports.
See: https://progress.opensuse.org/issues/97856
> Handle ChunkedEncodingError in browser.get

- openqa_review/openqa_review.py
- tests/todo-only/report-todo-only.md
Change job groups from list items to section headings for readability 
Corresponding Ticket: https://progress.opensuse.org/issues/97403
> Change job groups in todo_only report into section headers

- openqa_review/openqa_review.py
- tests/todo-only/report-todo-only.md
Job groups after the first one are indented, this is fixed by a line break
Also deleted a superfluous colon
This is followup on this: https://progress.opensuse.org/issues/97403
> Add line break after each job group to clean up formatting

- openqa_review/openqa_review.py
- tests/test_openqa_review.py
* Do not rely on the job details returned by openQA's API to be always
complete (and contain actually a softfail)
* Continue the search like in other error cases instead
* Cover error handling when finding bugrefs in softfailures
* See https://progress.opensuse.org/issues/101884
> Avoid throwing an `IndexError` or `KeyError` when details incomplete

- README.md
When trying to generate a coverage report, I got an error message:
```
tox -e cov
coverage html
Couldn't read data from '.../openqa_review/.coverage': UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 106: invalid start byte
```
So it's important to run the correct binary compatible with the one that generated the data.
> Document how to locally test

- openqa_review/openqa_review.py
...for Redmine issues.
And fix the check for last_comment_text because `if ""` is false in python.
Issues:
* https://progress.opensuse.org/issues/101722
* https://progress.opensuse.org/issues/102200
Fixes this error:
File "/usr/lib/python3.8/site-packages/openqa_review/openqa_review.py",
line 780, in last_comment
assert self.issue_type == "bugzilla"
> Ensure that last_comment_text is not None

- openqa_review/openqa_review.py
Issue: https://progress.opensuse.org/issues/102200
So far we only see:
ERROR:openqa_review.openqa_review:Error retrieving details for bugref
boo#1183044 (https://bugzilla.opensuse.org/show_bug.cgi?id=1183044):
'NoneType' object is not subscriptable
so we don't know where that exception actually happened.
This commit adds a traceback to the message.
I couldn't reproduce the issue locally so far, but adding the traceback might help us when it happens next time in production.
> Improve logging of TypeError

- openqa_review/browser.py
- openqa_review/openqa_review.py
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%255B%257B%2522ids%2522%253A%2B%255B9315715%255D%257D%255D
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%255B%257B%2522ids%2522%253A%2B%255B9315716%255D%257D%255D
- tests/test_openqa_review.py
Issue: https://progress.opensuse.org/issues/102200
Bugs not found are non-fatal and should be shown in the generated HTML,
but authentication errors should be fatal.
> Handle bugzilla jsonrpc errors

- openqa_review/openqa_review.py
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.comments%26params%3D%255B%257B%2522ids%2522%253A%2B%255B815%255D%257D%255D
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%255B%257B%2522ids%2522%253A%2B%255B0815%255D%257D%255D
- tests/progress/https%3A::progress.opensuse.org:issues:102440.json%3Finclude%3Djournals
- tests/test_openqa_review.py
* Avoid running into an assertion error when trying to find the latest
comment for an unsupported or erroneous bug reference
* Note that for progress issues the last comment info might *not* be set if
constructing the issue failed (resulting in an erroneous issue object)
* See https://progress.opensuse.org/issues/102440
> Prevent assertion when querying the last issue comment

- .github/workflows/python-package.yaml
Issue: https://progress.opensuse.org/issues/102350
What's not yet working: doctests
```
.tox/cov/bin/py.test --doctest-modules openqa_review                                                                                                                [p5.26.3] 20:01:45
============================================================================================================= test session starts ==============================================================================================================
platform linux -- Python 3.6.12, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/tina/openqa-devel/repos/openqa_review
plugins: mock-3.6.1, cov-2.12.0
collected 2 items / 2 errors …
```
> Add GitHub Workflow for testing

- README.md
* Add more details about `tox` environments
* Mention how to ensure correct formatting of files
* Keep information related to direct `pytest` invocations together (and
not mention how to generate the coverage report in the middle)
* Use subsections for the different parts
> Improve README section for running tests

- setup.py
As of version 20.3 pip requires PEP440 compliant version strings. Not
generating such a version leads to errors when trying to invoke `tox` in
environments which use a newer pip version.
I've been testing this change on a Git commit which is on a tag and one
that is not on a tag. If it is on a tag the tag is used as version (as
before). If it is not on a tag the most recent tag is used and the
development revision appended, e.g. "1.25.0.dev76" (before it would have
been "1.25.0-76-g777610a").
See
* https://github.com/pypa/pip/issues/9188
* https://progress.opensuse.org/issues/102584
> Create PEP440 version string on dev commits to fix problems running tox

- setup.py
This should fix the decoding error we see in OBS builds:
```
[   29s] Traceback (most recent call last):
[   29s]   File "setup.py", line 52, in <module>
[   29s]     long_description=open(os.path.join(os.path.dirname(__file__), "README.md")).read(),
[   29s]   File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
[   29s]     return codecs.ascii_decode(input, self.errors)[0]
[   29s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2366: ordinal not in range(128)
```
> Avoid assuming wrong character set when reading README.md

- .github/workflows/python-package.yaml
- README.md
- tox.ini
Issue: https://progress.opensuse.org/issues/102350
I added a tox plugin like requested from @okurz but also kept the style/coverage tests separate. This way we see immediately which extra test failed without having to dig into the test log.
> Improve GitHub workflow

- openqa_review/openqa_review.py
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%255B%257B%2522ids%2522%253A%2B%255B0815%255D%257D%255D
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.get%26params%3D%255B%257B%2522ids%2522%253A%2B%255B815%255D%257D%255D
Previously redmine would read out comments from the issue journal that
was retrieved along with the initial request. For bugzilla the comments
were requested "on-the-fly" when trying to get the "last comment" from
the issue object. To harmonize that and simplify the code I moved the
bugzilla comment reading into the initialization function so that the
actual requests are conducted more near to each other.
This commit changes the test data accordingly as we now need a valid bug
cache object for bug "815". Previously there was already a seemingly
unused cache file for bug "0815", mind the leading zero.
> Harmonize they way we query for redmine+bugzilla comments

- openqa_review/openqa_review.py
Note: use the `-r (--recreate)` flag when running tox to be sure to get the latest version of black:
`tox -e black -r`
> Fix formatting to make black happy

- openqa_review/openqa_review.py
* Simplify unformatted_str assignment with ternary operator
* Fix typo 'formated' in variable
> Fix formated spelling error

- openqa_review/openqa_review.py
- tests/bugzilla/:jsonrpc.cgi%3Fmethod%3DBug.comments%26params%3D%255B%257B%2522ids%2522%253A%2B%255B815%255D%257D%255D
- tests/progress/https%3A::progress.opensuse.org:issues:102440.json%3Finclude%3Djournals
- tests/progress/https%3A::progress.opensuse.org:issues:102442.json%3Finclude%3Djournals
- tests/test_openqa_review.py
The threshold computation defaults to exponential backoff taking into
account the delay between the last and second to last comment. The time
will be never less than MIN_DAYS_UNCHANGED days.
Include expected time until next reminder message.
Related ticket: https://progress.opensuse.org/issues/106907
> Compute the threshold for sending reminder

- .github/workflows/python-package.yaml
- tox.ini
The now latest Ubuntu no longer ships with 3.6.
> Run CI for Python 3.6 on Ubuntu 20.04

- README.md
Freenode is dead. Long live libera.chat!
> Update IRC link to libera.chat

- openqa_review/browser.py
- openqa_review/openqa_review.py
- tests/test_openqa_review.py
Unlike the login used so far, an API key needs to be included with the params passed to the API. Doing both at once should retain compatibility between Bugzilla versions.
See: https://progress.opensuse.org/issues/120525
> Inject Bugzilla API token into params

- openqa_review/openqa_review.py
A not encoded plus sign lead to an empty result because it is decoded into a space.
Issue: https://progress.opensuse.org/issues/126674
> Encode values in URLs

- .github/workflows/python-package.yaml
- openqa_review/browser.py
- openqa_review/openqa_review.py
- openqa_review/tumblesle_release.py
- tox.ini
Keep 3.6 for openSUSE Leap/SLE. Use more recent versions available in
openSUSE Tumbleweed as well as ubuntu-latest.
> tox: Update tested python versions

- openqa_review/openqa_review.py
- tests/test_openqa_review.py
Related progress issue: https://progress.opensuse.org/issues/106368
> Mention NO_REMINDER_REGEX as additional option to prevent reminders

- README.md
Just calling the script like this doesn't work, at least not with python 3.11:
% python openqa_review/openqa_review.py
Traceback (most recent call last):
File "path/to/openqa_review/openqa_review/openqa_review.py", line 110, in <module>
from .browser import Browser, DownloadError, BugNotFoundError, add_load_save_args  # isort:skip
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: attempted relative import with no known parent package
> Add commandline usage from git clone

- tox.ini
https://github.com/zheller/flake8-quotes/pull/111 is merged back in 2022
related poo: https://progress.opensuse.org/issues/184507
> Remove flake pinned version
